### PR TITLE
WebKit2

### PR DESCRIPTION
**Pull request by ptomato**
At long last, here's the current stable version of WebKit2. I'm still waiting on some patches to get reviewed on WebKit's bugzilla, but it's just not very high on the WebKit developers' priority list. They recently merged a few of the ones I had, and so I just decided to go ahead with this pull request and get a stable release in, build fixes notwithstanding, before something else breaks and I have to write even more WebKit patches.

This also requires a patch to gobject-introspection if you are building introspection bindings for WebKit: https://bugzilla.gnome.org/show_bug.cgi?id=625195 I've patched the tarball on modulesets-stable, but you'll have to add it manually to your git checkout if you are on modulesets or modulesets-unstable.

This allows us to build a recent version of DevHelp as well, so I've added that too.

All in all I thought it would be clearer to put the WebKit modules in their own file now, since they pull in quite a lot of dependencies that you won't otherwise need, so I've moved them from gtk-osx-unsupported.modules to gtk-osx-webkit.modules.

### CODE REVIEW

**Comment by jralls** [comment]
You got a bit aggressive with moving modules: Webkit isn't the only thing that needs the network stack or the spell-checking stack. Osm-gps-map at least needs the first and several applications need the latter.

What are the SDK requirements for Webkit2gtk3?

**Comment by ptomato** [comment]
> You got a bit aggressive with moving modules: Webkit isn't the only thing that needs the network stack or the spell-checking stack. Osm-gps-map at least needs the first and several applications need the latter.

Good point; I moved enchant into gtk-osx-random.modules because gtkspell also lives there. I can't find anything else in the repo that depends on libsoup, though. I wasn't aware anyone was building osm-gps-map for OSX. What do you think would be a good home for it?

> What are the SDK requirements for Webkit2gtk3?

How would I find that out short of building it on other SDKs? I believe it needs C++11 and libc++ (rather than libstdc++), but otherwise I think it uses Gnome APIs rather than OS X ones everywhere.

**Comment by jralls** [comment]
Gramps uses osm-gps-map. Maybe the right thing to do would be to rename gtk-osx-webkit.modules to gtk-osx-network.modules.

AFAIK there's no way except to try. The SDKs provide several generic Unix libraries as well as the OSX frameworks; it's the regular linking of those libraries that prevents using a current SDK with -macosx-version-min=10.5 from working, that magic works only on frameworks. Dyld barfs when it tries to load a dylib that's an older compatibility version from the one the program linked to when built. There's a work-around, of course: If a module requires a newer version of some system lib that the older SDK provides we can make a module for it. One example is libintl, where the Apple-provided 64-bit version is missing some symbols that glib uses.
Are you sure about libc++? That's an llvm thing and it surprises me that the WebkitGtk folks would lock out gcc. It first shows up in the Mac SDKs for v10.7, but without testing or exhaustive review there's no way of knowing if that version supports all of the C++11 features that WebkitGtk needs. For example, one needs clang 3.1 to get initializer lists and Xcode 4.3 has only clang 3.0.

**Comment by ptomato** [comment]
> Maybe the right thing to do would be to rename gtk-osx-webkit.modules to gtk-osx-network.modules.

Done.

> Are you sure about libc++? That's an llvm thing

I should amend what I said; if you want to compile it with Clang, it seems to require libc++ rather than libstdc++. Presumably with GCC libstdc++ will still work.

**Pull request merged**
