### PR TITLE
itstool 2.0.7, libxml2 2.11.5

### PR DESCRIPTION
**Pull request by totaam**
Split from #95

### CODE REVIEW

**Comment by jralls** [comment]
@totaam Why did you close these?

**Comment by totaam** [comment]
Oops, I think GitHub closed it when I deleted the branch..
I'll try to reinstate it tomorrow.

**Comment by jralls** [comment]
Yeah, if you delete the branch then there's nothing for the PR to work with so it gets closed.

**Comment by totaam** [comment]
I don't think I can re-open this PR - even with the branch force-pushed.
So I had to make a new PR: #104

**Pull request closed without merging**
