### PR TITLE
Python updates: Python 3.11.9 and Pygments 2.16.1

### PR DESCRIPTION
**Pull request by totaam**

### CODE REVIEW

**Comment by jralls** [comment]
Thanks. I did notice an oddity, though: Python linked the libpython in my venv. I noticed because python3 --version returned 3.11.7 instead of 3.11.9. Changing the dyld link with install_name_tool fixed it.

Did you see anything like that?

**Comment by totaam** [comment]
Oh, now that's interesting.
My venv has the same Python version, so I wouldn't necessarily notice.
Which exact `install_name_tool` did you use to fix it?
Can we automate this? Or prevent it somehow?
(this may explain some oddities with python modules dependency resolution)

**Comment by jralls** [comment]
`install_name_tool -change /path/to/venv/lib/libpython3.11.dylib $PREFIX/lib/libpython3.11.dylib $PREFIX/bin/python3`.

You can check your build with `otool -L $PREFIX/bin/python3 | grep libpython3.11.dylib`.

It's a hack, not something we want to automate. We need to figure out why `make install` is picking the wrong path and fix that.

**Comment by jralls** [comment]
Curiouser and curiouser. I just built gtk3 from  modulesets-unstable with python3 early in the build sequence instead of at the end and it linked the right libpython3.11.dylib. Yesterday I'd built through meta-gtk-osx-gtk3 with the venv's python then built meta-gtk-osx-python3-gtk3.

**Pull request merged**
