### PR TITLE
For upstream

### PR DESCRIPTION
**Pull request by totaam**
Replaces #80 with the following changes:
* rebased
* also updating: GStreamer 1.22.0, gobject-introspection 1.72.1, libffi 3.4.4 and libpng 1.6.39
* squashed Python 3.10 commits as requested

As for why I chose Python 3.10.10 over 3.11.2 - I'm just being conservative here, I could bump it too if you like.

FWIW: works for me(tm).

### CODE REVIEW

**Comment by jralls** [comment]
Thanks.

BTW, you don't have to make a new PR after a rebase, just force-push to the original PR's branch to replace the commits.

**Comment by jralls** [comment]
@totaam [Xpra-org#22](https://github.com/Xpra-org/gtk-osx-build/issues/22) looks a bit confused. The crash report shows libpython3.9 while in the first comment you talk about a problem with libffi-3.4 vs. 3.3 and something being fixed in libpython 3.10.1; the modulesets before your PR had python 3.10.2 and libffi 3.4.3. 

It seems possible, likely even, that you have at least one library conflict. Try a completely fresh build in an empty prefix before you decide that the problem is really with the upgrade from libffi 3.4.3 to libffi 3.4.4.

**Comment by totaam** [comment]
@jralls the github issue was created at a time when `python3.9` was the version I was using for building but I have switched to `python3.10` a while back now.

I did do a fresh build in an empty prefix, not just once, but twice - once on a MacOS 10.14.x VM and once on a MacOS 12.x VM. In both cases, downgrading `libffi` resolved the crashes.

The downgrade I did was from 3.4.4 back to 3.3, I don't know yet if earlier versions of 3.4.x are affected - based on the links in https://github.com/Xpra-org/gtk-osx-build/issues/22, I suspect that they are. Hence: https://github.com/jralls/gtk-osx-build/pull/85

No worries if you want to wait for more evidence before applying a downgrade.

**Comment by jralls** [comment]
@totaam i took the time to read through your xpra bug and the very interesting conda-forge one. You mentioned on your xpra one yesterday

> Alternatively, we could try building Python ./configure --with-system-ffi as per https://bugs.python.org/issue44556

Have you tried that? Maybe the right answer is to not build libffi at all and always depend on the SDK one. I looked through my archived Xcodes and found that libffi was first included in Xcode 8. ffi.h in that through Xcode 10 indicate an ancient version:
>    libffi PyOBJC - Copyright (c) 1996-2003  Red Hat, Inc.

Xcode 11 and 12 say
>  libffi 3.3-rc0 - Copyright (c) 2011, 2014 Anthony Green
                    - Copyright (c) 1996-2003, 2007, 2008 Red Hat, Inc.

I don't have an Xcode 13 handy, but Xcode 14's starts with
>   libffi 3.4-rc1
     - Copyright (c) 2011, 2014, 2019, 2021 Anthony Green
     - Copyright (c) 1996-2003, 2007, 2008 Red Hat, Inc.

Indicating that builds on Xcode 14 (and maybe 13) might have the opposite problem.

Yeah, more exploration is necessary before deciding on the right fix.

**Comment by totaam** [comment]
> >  `./configure --with-system-ffi` as per https://bugs.python.org/issue44556

> Have you tried that?

Not yet, I was going to but I am seriously overloaded ATM and not helped by the fact that my MacOS VMs only run on a single core (of an old CPU at that) so trying anything takes a looong time.

FYI, in xpra `libffi` is used by `python3`, `gobject-introspection`, `python-cffi` and `pyobjc` - and maybe more I haven't spotted yet.

**Comment by totaam** [comment]
@jralls I've side-stepped the `libffi` issue but you may be interested in this comment: https://github.com/Xpra-org/gtk-osx-build/issues/27#issuecomment-1679924630

**Comment by jralls** [comment]
@totaam I did. You should post that in an [issue to libffi](https://github.com/libffi/libffi/issues); I haven't done a comprehensive search to see if there's already an open one, but there are a *lot*, many appear to be quite serious.

 but I found the *next* comment even more interesting: " I raised the minimum requirements to MacOS 12: ". Since that has libffi 3.4 what does that imply for your preferred version of libffi here?

**Comment by jralls** [comment]
One more thing: For any rollback we have to take Apple Silicon support into account. I imagine that's why the version in Xcode got bumped to 3.4.0-rc1.

**Pull request merged**
