### PR TITLE
Gtk updates: librsvg, graphene, harfbuzz, gobject-introspection, cairo, freetype

### PR DESCRIPTION
**Pull request by totaam**
* librsvg 2.57
* graphene 1.10.8
* harfbuzz 8.3.0
* gobject-introspection 1.78.1
* cairo 1.18.0
* freetype 2.13.2

### CODE REVIEW

**Comment by jralls** [comment]
I'm amused that you called the PR Gtk updates but didn't update the Gtk modules.

**Comment by jralls** [comment]
> I am not brave enough to touch the Gtk bits, I'll leave that to you!
Maybe I should have called this "timid Gtk minor dependencies updates"?

Heehee.

Next, I don't understand why free type needs to disable brotli or the circular dependency comment. We don't build Brotli so FindBrotliDec should fail (unless a user has installed it some other way, perhaps because they want WOFF2 font support). I also don't see any dependencies at all in [brotli's CMakeLists.txt](https://github.com/google/brotli/blob/master/CMakeLists.txt). How is there a circular dependency?

**Comment by totaam** [comment]
> We don't build Brotli so FindBrotliDec should fail (unless a user has installed it some other way

We do for xpra! (used for opportunistic clipboard text data compression)
https://github.com/Xpra-org/gtk-osx-build/blob/be6c14152d0df9a52e061847fa43fb62b60e058b/xpra-tools.modules#L92-L97

I wished I had recorded more details about the breakage in the commit or issue it links to:
https://github.com/Xpra-org/gtk-osx-build/commit/c2e8ca9e8769c2490134cebcdac78a3cb2ed9443

This does not help (it pre-dates the problem):
https://github.com/Xpra-org/gtk-osx-build/commit/78501f83813125195ee730149fdbfa512439381d

So I've removed this part of the commit and force pushed this branch.

---

And... as I reviewed the diff before commenting, I also spotted issues with `glib`:
* `-Dtests=false` added to the `mesonargs`.
And you were probably going to ask me to fix it - and I don't think I can, I did try.
This is the upstream issue: [GLib >= 2.73.2 Fails to build with "implicit declaration of function 'g_osx_app_info_get_type'" error on macOS 10.15.7 Catalina](https://gitlab.gnome.org/GNOME/glib/-/issues/2902)
* I had also forgotten to include the updated glib intl patch: https://github.com/Xpra-org/gtk-osx-build/commit/326b01489b563923f5d31d503c3841deb7bf6622

So I have now also removed the glib update from this PR
(I've got this nagging feeling that the 2.78 update fixes something else though..)
If you're OK with `-Dtests=false`, I can make a new PR for glib 2.78.1

**Comment by jralls** [comment]
@totaam The gio test failure was fixed by https://gitlab.gnome.org/GNOME/glib/-/commit/28835733a2362be91cd66e758162adbac5058d78, which is included in glib 2.80.0. The current glib stable release is [2.80.2](https://download.gnome.org/sources/glib/2.80/glib-2.80.2.tar.xz) so that's what you should be updating to, no need to disable tests.

As for brotli in your Xpra build, OK, though that still doesn't explain the circular dependency: Your brotli module has none. (BTW, there's a leftover `autogen-sh` attribute in the `cmake` element.)  The right way to disable for your build it is to add
```
   module_cmakeargs[`freetype']='-DFT_DISABLE_BROTLI=ON'
```
to jhbuildrc-custom.

**Comment by totaam** [comment]
You can ignore the "circular dependency" thing, it was just a rpath issue.

**Comment by totaam** [comment]
I have created a new PR for glib: #100
If you want me to include it in this PR instead, just let me know.

BTW, I noticed that there are quite a few [patches](https://github.com/jralls/gtk-osx-build/tree/master/patches) that seem to be orphaned.
Would you take a PR to delete unused patches? (a shell script to find the unused ones should be easy enough to write)

**Comment by jralls** [comment]
> If you want me to include it in this PR instead, just let me know.

Either way works fine, so I'm sure you can find a better use of your time.

> Would you take a PR to delete unused patches? 

Of course.

**Pull request merged**
