### PR TITLE
Update to jhbuild master

### PR DESCRIPTION
**Pull request by lazka**
* Remove the autoreconf patch which is already upstream
* Update the bootstrap module to work with the newer jhbuild
* Move readline into the bootstrap module as it is a dependency of bash

### CODE REVIEW

**Comment by jralls** [comment]
Fred went for your "bootstrap" attribute change rather easily but you didn't come up on gtk-osx-users like I asked you to to explain why exactly you need it. I think that you're doing something wrong and that it's not necessary, so you need to explain it if you want me to accept that part of your change. The other parts of this PR make sense, so I'd like you to separate it into two PRs, one for the autoreconf patch and the readline move and the other for the bootstrap attribute. The latter needs a very detailed explanation of what you're doing and why there needs to be a bootstrap attribute on every module in the bootstrap moduleset.

**Comment by lazka** [comment]
Sure, sorry for not providing more info.

A little back story: I by accident tried to use gtk-osx with a jhbuild master checkout and bootstrap failed. I tried to fix it and then noticed that gtk-osx uses an old ~2013 checkout from jhbuild. So this is all optional... but I guess reducing the differences from gtk-osx to jhbuild can't hurt.

The problem with jhbuild master is the following commit: https://git.gnome.org/browse/jhbuild/commit/?id=e92634aaba2f93ae809d848f9bcef7882166e7e9
It adds default packages to jhbuild (called virtual sysdeps there) and uses them as default dependencies for the different module types. So for example `<autotools/>` now depends on automake/libtool/make. This makes automake and all its dependencies depend on themselves resulting in dependency cycles which makes jhbuild bootstrap fail.

If you have another idea how to fix this I'd like to hear it.

For splitting up the PR, the autoreconf/bootstrap changes are a result of using a newer jhbuild so they need to stay together. The readline change I can split out.

Thanks for the reviews.

**Comment by jralls** [comment]
> For splitting up the PR, the autoreconf/bootstrap changes are a result of using a newer jhbuild so they need to stay together. The readline change I can split out.

So the title of the change should be "Update jhbuild commit to recent master." Removing the autoreconf patch and adding the bootstrap attributes is a side effect of that change.

I think it would have been better to make the virtual dependency generation dependent on a flag that build.py sets and bootstrap.py doesn't. That wouldn't have required changes to the modulesets. 

But why doesn't the jhbuild-included bootstrap.modules have this problem? It's also building autoconf, libtool, and a variety of automakes,

**Comment by lazka** [comment]
> So the title of the change should be "Update jhbuild commit to recent master." Removing the autoreconf patch and adding the bootstrap attributes is a side effect of that change.

Sounds better, thanks.

> I think it would have been better to make the virtual dependency generation dependent on a flag that build.py sets and bootstrap.py doesn't. That wouldn't have required changes to the modulesets. 

Currently the bootstrap command is just a hardcoded moduleset/module [0] behaving the same as jhbuild build. I think special casing it would make it harder to debug jhbuild compared to the explicitness of the moduleset changes.

Are the changes to the modulesets a problem for existing users?

> But why doesn't the jhbuild-included bootstrap.modules have this problem? It's also building autoconf, libtool, and a variety of automakes, 

It does and I also applied the same changes upstream: https://git.gnome.org/browse/jhbuild/commit/?id=d7820ee9599bea33a5a62e2847371b312083b64f

(output without disabling the deps)
```
W: Circular dependencies detected: meta-bootstrap -> xz -> automake -> autoconf -> m4 -> automake
W: Circular dependencies detected: meta-bootstrap -> xz -> automake -> autoconf -> automake
W: Circular dependencies detected: meta-bootstrap -> xz -> automake -> automake
W: Circular dependencies detected: meta-bootstrap -> xz -> libtool -> libtool
```

Note the upstream jhbuild doesn't really have a bootstrap step anymore and only enables it for osx, so I guess nobody noticed: https://git.gnome.org/browse/jhbuild/tree/modulesets/bootstrap.modules?id=d7820ee9599bea33a5a62e2847371b312083b64f#n190

[0] https://git.gnome.org/browse/jhbuild/tree/jhbuild/commands/bootstrap.py#n23

**Comment by jralls** [comment]
So an even better approach would have been a "disable virtual dependencies" option to cmd_build, which bootstrap.py could invoke and which users who don't want that behavior for whatever reason could also use.

Jhbuild obviously still has the bootstrap step, it's just not used on Linux where it's been replaced by sysdeps. That obviously makes sense on Linux, there's no reason to build the toolchain from source when the distro's packages will do the job. Last I checked in with Ryan about bootstrap, though, he was using it on BSD. Perhaps he has since gotten sysdeps working there too and no longer needs it.  

Weird about the change: Before I wrote that comment I checked bootstrap.modules in git.gnome.org and didn't see the bootstrap attrs. I must have managed to get a view from an earlier commit somehow.
No, the attribute flag doesn't affect anyone; updating jhbuild might.

If the upstream bootstrap.modules is really being used only for OS X maybe gtk-osx should drop bootstrap.modules altogether... or maybe disappear completely if jhbuild's modulesets work correctly.

**Comment by lazka** [comment]
> So an even better approach would have been a "disable virtual dependencies" option to cmd_build, which bootstrap.py could invoke and which users who don't want that behavior for whatever reason could also use.

A downside of this would be that any autotools packages in bootstrap would need to explicitly depend on autmake.

> Jhbuild obviously still has the bootstrap step, it's just not used on Linux where it's been replaced by sysdeps. That obviously makes sense on Linux, there's no reason to build the toolchain from source when the distro's packages will do the job. Last I checked in with Ryan about bootstrap, though, he was using it on BSD. Perhaps he has since gotten sysdeps working there too and no longer needs it.

yeah, I remember desrt saying that bootstrap should ideally not be needed at all..

> Weird about the change: Before I wrote that comment I checked bootstrap.modules in git.gnome.org and didn't see the bootstrap attrs. I must have managed to get a view from an earlier commit somehow.

> No, the attribute flag doesn't affect anyone; updating jhbuild might.

At least in my case I can report that I build python+gtk+gst over the last year with it wihtout problems. Thanks for catching the disable_Werror problem. I had it in my jhbuildrc but didn't know that it was needed because of the newer jhbuild.

> If the upstream bootstrap.modules is really being used only for OS X maybe gtk-osx should drop bootstrap.modules altogether... or maybe disappear completely if jhbuild's modulesets work correctly.

Yeah, having some untested moduleset upstream isn't good. But I guess if someone wants to port/use jhbuild on a new platform it can be useful as a starting point.

Thanks for reviewing/merging. If there is any fallout feel free to ping me and I'll have a look.

**Comment by jralls** [comment]
I've merged this after splitting out the readline change and adding disable_Werror = false to jhbuildrc-gtk-osx. The last is needed because at least one module, zlib, pukes if you pass --disable-Werror to configure.

**Pull request closed without merging**
