### PR TITLE
GStreamer 1.22.5

### PR DESCRIPTION
**Pull request by totaam**
Trivial minor update, also bumps orc to 0.4.34

### CODE REVIEW

**Comment by jralls** [comment]
modulesets/gtk-osx-gstreamer.modules needs corresponding updates.

**Comment by totaam** [comment]
Done.

**Comment by jralls** [comment]
That was fast. Thanks!

**Comment by jralls** [comment]
BTW and somewhat germane to this is [this issue about building on Apple Silicon](https://gitlab.gnome.org/GNOME/gtk-osx/-/issues/76). I don't suppose you have an Apple Silicon mac to test on?

**Comment by totaam** [comment]
I do have access to one via ssh.
This PR was build-tested on it.
What else would you like me to test?

**Comment by jralls** [comment]
OK, thanks. That explains why you haven't updated either ffmpeg or gst-libav.

**Pull request merged**
